### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Saturnix** [rofl0r/nat-tunnel#4]
OS: Windows 10
Python 3.7.2

`C:\Users\Me\AppData\Local\Programs\Python\Python37\python.exe "C:\Program Files (x86)\nat-tunnel-master\natsrv.py" --mode client --secret hunter1 --local 192.168.1.117:123 --admin xxx.xxx.xxx.xxx:321`

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 258, in <module>
    cl.setup()
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 75, in setup
    self.controlsock = self._setup_sock('adm')
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 69, in _setup_sock
    sock.connect()
  File "C:\Program Files (x86)\nat-tunnel-master\rocksock.py", line 242, in connect
    for pnum in xrange(1, len(self.proxychain)):
NameError: name 'xrange' is not defined
```

Possible reason: https://stackoverflow.com/a/17192181/1307020

**Comment by rofl0r** [comment]
thanks! does this commit 95ecc4b fix the issue for you ?

**Comment by Saturnix** [comment]
Yes, but now I get:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 258, in <module>
    cl.setup()
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 75, in setup
    self.controlsock = self._setup_sock('adm')
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 70, in _setup_sock
    nonce = sock.recv(NONCE_LEN*2 + 1).rstrip('\n')
  File "C:\Program Files (x86)\nat-tunnel-master\rocksock.py", line 316, in recv
    data += chunk
TypeError: can only concatenate str (not "bytes") to str
```

So I tried to change line 298 of rocksock.py from `data = ''` to` data = b''` and I get:


```
Traceback (most recent call last):
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 258, in <module>
    cl.setup()
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 75, in setup
    self.controlsock = self._setup_sock('adm')
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 70, in _setup_sock
    nonce = sock.recv(NONCE_LEN*2 + 1).rstrip('\n')
TypeError: a bytes-like object is required, not 'str'
```


Tried changing (in lines 70 and 71 of natsrv.py):

```
nonce = sock.recv(NONCE_LEN*2 + 1).rstrip('\n')
sock.send(_hash(cmd + self.secret + nonce) + '\n')

```
to 

```
nonce = sock.recv(NONCE_LEN*2 + 1).rstrip(b'\n')
sock.send(_hash(cmd + self.secret + nonce) + b'\n')
```


and I get:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 258, in <module>
    cl.setup()
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 75, in setup
    self.controlsock = self._setup_sock('adm')
  File "C:\Program Files (x86)\nat-tunnel-master\natsrv.py", line 71, in _setup_sock
    sock.send(_hash(cmd + self.secret + nonce) + b'\n')
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by schtritoff** [comment]
Regarding python3 - on Ubuntu 20.04.3 LTS (Focal Fossa) + Python 3.8.10 it works, but on other system I still have errors.


OS: Manjaro Linux (arch),  Linux 5.4.150-1-MANJARO x86_64
Python 3.9.7

server
```
Traceback (most recent call last):
  File "/root/nat-tunnel/natsrv.py", line 252, in <module>
    srv = NATSrv(args.secret, adminip, int(adminport), clientip, int(clientport))
  File "/root/nat-tunnel/natsrv.py", line 133, in __init__
    self.hashlen = len(_hash(""))
  File "/root/nat-tunnel/natsrv.py", line 9, in _hash
    return hashlib.sha256(str).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

client
```
Traceback (most recent call last):
  File "/root/nat-tunnel/natsrv.py", line 258, in <module>
    cl.setup()
  File "/root/nat-tunnel/natsrv.py", line 75, in setup
    self.controlsock = self._setup_sock('adm')
  File "/root/nat-tunnel/natsrv.py", line 70, in _setup_sock
    nonce = sock.recv(NONCE_LEN*2 + 1).rstrip('\n')
  File "/root/nat-tunnel/rocksock.py", line 316, in recv
    data += chunk
TypeError: can only concatenate str (not "bytes") to str
```

So it seems that python 3.8 is ok, but fails on 3.9 ?

**Comment by rofl0r** [comment]
>    self.controlsock = self._setup_sock('adm')

this was changed in git, it appears you're running an older version on that manjaro box ?

**Comment by schtritoff** [comment]
Yeah, my fault. Forgot to git pull origin mastet on that machine... Sorry and thanks for nice simple solution.
